// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAEcGPpy1EKaLYyJlK-SKubGApXK1HtXQ',
    appId: '1:846137278053:web:754dd19e23a77da25bd08c',
    messagingSenderId: '846137278053',
    projectId: 'team-f-3-bootcamp-project',
    authDomain: 'team-f-3-bootcamp-project.firebaseapp.com',
    databaseURL: 'https://team-f-3-bootcamp-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'team-f-3-bootcamp-project.appspot.com',
    measurementId: 'G-V71FBD0TYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANj_x59fIp7K83D0pxWcm8k-nKaouuYYY',
    appId: '1:846137278053:android:e71c15b6a1c48f8c5bd08c',
    messagingSenderId: '846137278053',
    projectId: 'team-f-3-bootcamp-project',
    databaseURL: 'https://team-f-3-bootcamp-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'team-f-3-bootcamp-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADXGu6MzCqhnp9T17nKkA4cD3GTlf9imY',
    appId: '1:846137278053:ios:dcabeae1703dff535bd08c',
    messagingSenderId: '846137278053',
    projectId: 'team-f-3-bootcamp-project',
    databaseURL: 'https://team-f-3-bootcamp-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'team-f-3-bootcamp-project.appspot.com',
    androidClientId: '846137278053-4ebrgji7o4b4fg5uu7p67mj3h2th078k.apps.googleusercontent.com',
    iosClientId: '846137278053-3j152kb33v28cmb7chl9gdoa8dtjg182.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourselfInTimeProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADXGu6MzCqhnp9T17nKkA4cD3GTlf9imY',
    appId: '1:846137278053:ios:dcabeae1703dff535bd08c',
    messagingSenderId: '846137278053',
    projectId: 'team-f-3-bootcamp-project',
    databaseURL: 'https://team-f-3-bootcamp-project-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'team-f-3-bootcamp-project.appspot.com',
    androidClientId: '846137278053-4ebrgji7o4b4fg5uu7p67mj3h2th078k.apps.googleusercontent.com',
    iosClientId: '846137278053-3j152kb33v28cmb7chl9gdoa8dtjg182.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourselfInTimeProject',
  );
}
